spring.application.name=Chatbot


# Read dynamic port assigned by cloud, fallback to 8080 locally
server.port=${PORT:8080}


# Ollama Configuration
# Default local URL for Ollama
spring.ai.ollama.base-url=http://localhost:11434

# Specify the model you pulled via: ollama run <model_name>
spring.ai.ollama.chat.options.model=llama3.2

spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp
